In [ ]:
### broadcasting
import numpy as np

A = np.arange(2,10,2).reshape(2,2)
print(A, A.shape)

print()

B = np.ones((2,2),dtype=np.int32)*2
print(B, B.shape)

[[2 4]
 [6 8]] (2, 2)

[[2 2]
 [2 2]] (2, 2)


In [ ]:

## elementwise임에 유의

print(A+B)
print()
print(A-B)
print()
print(A*B)
print()
print(A/B)

[[ 4  6]
 [ 8 10]]

[[0 2]
 [4 6]]

[[ 4  8]
 [12 16]]

[[1. 2.]
 [3. 4.]]


In [8]:
## 행렬곱

# np.dot(A, B) or A.dot(B) or A@B

print(np.dot(A,B))

[[12 12]
 [28 28]]


In [14]:
A = np.arange(1,7).reshape(3,2)
print(A, A.shape)

print()

B = np.arange(1,5).reshape(2,2)
print(B, B.shape)

print()

print(A.dot(B))


[[1 2]
 [3 4]
 [5 6]] (3, 2)

[[1 2]
 [3 4]] (2, 2)

[[ 7 10]
 [15 22]
 [23 34]]


브로드 캐스팅의 시작

In [ ]:
# 브로드 캐스팅 가능 여부: 차원표기상 두 행렬(차원이 적은 쪽은 앞에 1을 여러번 붙여 두 행렬의 차원을 맞춘다)의 각 차원의 값을 비교할 때 둘 중 하나가 1이거나 둘 다 같은 경우는 가능.

A = np.arange(1, 121).reshape(2,3,4,5)
B = np.arange(1,6)
print(A.shape)
print(B.shape)

print()

print(A+B)

(2, 3, 4, 5)
(5,)

[[[[  2   4   6   8  10]
   [  7   9  11  13  15]
   [ 12  14  16  18  20]
   [ 17  19  21  23  25]]

  [[ 22  24  26  28  30]
   [ 27  29  31  33  35]
   [ 32  34  36  38  40]
   [ 37  39  41  43  45]]

  [[ 42  44  46  48  50]
   [ 47  49  51  53  55]
   [ 52  54  56  58  60]
   [ 57  59  61  63  65]]]


 [[[ 62  64  66  68  70]
   [ 67  69  71  73  75]
   [ 72  74  76  78  80]
   [ 77  79  81  83  85]]

  [[ 82  84  86  88  90]
   [ 87  89  91  93  95]
   [ 92  94  96  98 100]
   [ 97  99 101 103 105]]

  [[102 104 106 108 110]
   [107 109 111 113 115]
   [112 114 116 118 120]
   [117 119 121 123 125]]]]


In [18]:
# 브로드 캐스팅이 안 되는 경우 예: (1,4), (3.) 

A = np.arange(1,5).reshape(1,4)
print(A.shape)

B = np.arange(1,4)
print(B.shape)

print(A+B)

(1, 4)
(3,)


ValueError: operands could not be broadcast together with shapes (1,4) (3,) 

In [21]:
# 브로드캐스팅 가능 (3,4), (4, )

A = np.arange(1, 13).reshape(3,4)
B = np.arange(1,5)
print(A+B)



[[ 2  4  6  8]
 [ 6  8 10 12]
 [10 12 14 16]]


추가하는 축 방향으로 배열을 복붙하는게 원리임. 1로 맞추는 건 차원추가, 이를 행렬 사이즈가 동일해질 때 까지 복붙. 그래서 차원값이 같은 경우와 1인 경우만 계산가능. 
# 요컨데 핵심은 행렬이 선형종속(복붙이니)이 되도록 행이나 열을 만드는 것이다.