In [1]:
import numpy as np

In [4]:
a = np.array([1,2])
print(np.linalg.norm(a))

print(np.sqrt(np.dot(a,a)))

2.23606797749979
2.23606797749979


In [ ]:
#항등행렬

import numpy as np
A = np.arange(1, 10).reshape(3,3)
print(A)

print()

I = np.eye(3,3,dtype=np.int32)
print(I)

print()

#행렬곱셈에 대한 항등원
print((np.dot(A,I)==A).all())
print((np.dot(I,A)==A).all())

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 0 0]
 [0 1 0]
 [0 0 1]]

True
True


In [ ]:
#역행렬

A = np.arange(1,5).reshape(2,2)
print(A)

print()

invA = np.linalg.inv(A)
print(invA)

print()

I = np.dot(A,invA)
print(I)

print()

#근사값으로 나오니까 불필요한 소수점 제거
print(np.round(I))

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]

[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]

[[1. 0.]
 [0. 1.]]
